from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Doctor)
admin.site.register(LeanerPhysician)
admin.site.register(ExpertPhysician)
admin.site.register(Log)
admin.site.register(VirtualPatient)
admin.site.register(ClinicalCase)
admin.site.register(VirtualCase)
admin.site.register(Feedback)
admin.site.register(Hypothesis)
admin.site.register(Question)
admin.site.register(PersonalInfo)
admin.site.register(TreatmentInProgress)
admin.site.register(Media)
admin.site.register(PhysicalDiagnosis)
admin.site.register(Exam)
admin.site.register(TypeParameter)
admin.site.register(MedicalParameter)
admin.site.register(LifeStyle)
admin.site.register(PhysicalActivity)
admin.site.register(Addiction)
admin.site.register(Travel)
admin.site.register(Symptom)
admin.site.register(MedicalAntecedent)
admin.site.register(ObstetricalAntecedent)
admin.site.register(Surgery)
admin.site.register(Allergy)
admin.site.register(Treatment)
admin.site.register(Disease)