# Generated by Django 4.0.4 on 2022-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_remove_treatmentinprogress_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialty',
        ),
    ]
