# Generated by Django 4.0.4 on 2022-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdisease',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ratingsystem',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weightdiseasesystem',
            name='rating_disease',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weightdiseasesystem',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weightsymptomdisease',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
