# Generated by Django 4.0.4 on 2022-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0002_alter_ratingdisease_rating_alter_ratingsystem_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdisease',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ratingsystem',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weightdiseasesystem',
            name='rating_disease',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
