# Generated by Django 4.0.4 on 2022-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0003_alter_ratingdisease_rating_alter_ratingsystem_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
