# Generated by Django 4.0.4 on 2022-05-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0004_alter_disease_name_alter_symptom_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightdiseasesystem',
            name='rating_disease',
        ),
        migrations.AddField(
            model_name='ratingdisease',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learner_app.system'),
        ),
    ]
