# Generated by Django 4.0.4 on 2022-06-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '__first__'),
        ('learner_app', '0005_remove_weightdiseasesystem_rating_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdisease',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.leanerphysician'),
        ),
        migrations.AlterField(
            model_name='ratingsystem',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.leanerphysician'),
        ),
    ]
